version: 2

defaults: &defaults
  working_directory: ~/xewards-delivery-hub-dispatcher
  docker:
    - image: alpine:3.8

jobs:
  build:
    <<: *defaults
    steps:
      - checkout

      - run:
          name: Instalar NODE e NPM
          command: apk add --update nodejs nodejs-npm

      - run:
          name: Instalar dependÃªncias
          command: npm install

      - run:
          name: Executar test
          command: npm test
